### ISSUE TITLE
Front Page!

### ISSUE THREAD

**Issue by anthonyshew** [anthonyshew/devtionary#4]
Hey, everyone! Who wants to volunteer to make a custom front page for Devtionary?

You've got two options:
1) Own this completely as designer and developer.
2) I can have my sister make you up a design to build and you can build it.

Comment below if you want to handle it and let me know if you need a design done!

**Comment by malcolmkiano** [comment]
I can handle this (including design) :)

**Comment by malcolmkiano** [comment]
This issue is complete as of #20

**Comment by anthonyshew** [comment]
Yes! Closed in #20.

**Comment by anthonyshew** [comment]
It looks like certain dimensions in the browser aren't happy with the background as it is currently set up. 

@malcolmkiano Do you want to take a look?

**Comment by anthonyshew** [comment]
Closed in #25
